version: '3.3'
services:
  pcapp:
    depends_on:
      - mysql
    container_name: pcapp
    build: 
      context: .
      dockerfile: Dockerfile.pcapp
    ports: 
      - "8181:8181"
    restart: always
  mysql:
    container_name: mysql
    image: mysql:latest
    ports:
      - "3306:3306"
    env_file:
      - ./mysql.env
    volumes:
      - myappvol:/var/lib/mysql
    restart: always
volumes:
  myappvol: